# -*- coding: utf-8 -*-
"""week1_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aa1o2h92Ovl3ODfsT2p6q4BHRV6RGm21

# Task 1: User Data Collector
"""

def collect_user_data():
    print("Let's collect some info!")
    name = input("Name: ")
    age = input("Age: ")
    email = input("Email: ")
    fav_num = input("Favorite Number: ")

    if "@" in email and "." in email:
        valid_email = email
    else:
        valid_email = "Invalid email"

    data = {"Name": name, "Age": age, "Email": valid_email, "Favorite Number": fav_num}

    print("\nYour Data:")
    for key, value in data.items():
        print(f"{key}: {value}")

collect_user_data()

"""  # Task 2 : Even or Odd"""

def is_even(num):
    return num % 2 == 0

try:
    n = int(input("Enter a number: "))
    if is_even(n):
        print(f"{n} is even!")
    else:
        print(f"{n} is odd!")
except:
    print("That wasn't a valid integer!")

"""# Task 3: Temperature Converter"""

def convert_temperature(temp, scale):
    if scale.upper() == "C":
        return (temp * 9/5) + 32, "F"
    elif scale.upper() == "F":
        return (temp - 32) * 5/9, "C"
    else:
        return None, None

try:
    temp_value = float(input("Enter a temperature: "))
    scale = input("Is it in Celsius (C) or Fahrenheit (F)? ")
    converted, target = convert_temperature(temp_value, scale)
    if converted is None:
        print("Please use 'C' or 'F'.")
    else:
        print(f"{temp_value}{scale.upper()} is {converted:.2f}{target}.")
except:
    print("Invalid input!")

"""# Task 4: Finding Min & Max"""

numbers = []
while len(numbers) < 5:
    try:
        num = float(input(f"Enter number {len(numbers)+1} of 5: "))
        numbers.append(num)
    except:
        print("Please enter a valid number!")
print("Numbers:", numbers)
print("Minimum:", min(numbers))
print("Maximum:", max(numbers))

"""# Task 5: Student Data Manager"""

students = []
for i in range(3):
    print(f"\nStudent {i+1}")
    name = input("Name: ")
    age = input("Age: ")
    grade = input("Grade: ")
    students.append((name, age, grade))

student_dict = {name: (age, grade) for name, age, grade in students}
print("\nStudent Data:")
for name, (age, grade) in student_dict.items():
    print(f"{name}: Age {age}, Grade {grade}")

"""# Task 6: Inventory Management System"""

def update_inventory(inv, item, change):
    inv[item] = max(0, inv.get(item, 0) + change)
    return inv

inventory = {"apple": 10, "banana": 20, "orange": 15, "grape": 12, "mango": 8}
print("Starting Inventory:")
for item, qty in inventory.items():
    print(f"{item}: {qty}")

for i in range(3):
    print(f"\nUpdate {i+1}")
    item = input("Item name: ")
    try:
        change = int(input("Change (positive to add, negative to remove): "))
        inventory = update_inventory(inventory, item, change)
    except:
        print("Please enter a valid integer!")
print("\nUpdated Inventory:")
for item, qty in inventory.items():
    print(f"{item}: {qty}")